version: '3.8'

networks:
  internal:
    driver: bridge

services:
  app:
    build: ./
    command: ./app
    restart: always
    networks:
      - internal
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - DB_PASSWORD=qwerty
  db:
    restart: always
    image: postgres
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/
    networks:
      - internal
    ports:
      - 5436:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    command: postgres -c 'shared_preload_libraries='
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    ports:
    - "6379:6379"
    depends_on:
      - db
